(asdf:defsystem :hackmode-tests
  :description "Regression tests for Hackmode core state, asset lifecycle, and expert reasoning"
  :depends-on (#:hackmode #:hackmode-database)
  :serial t
  :components ((:file "tests/core-state")
               (:file "tests/functions")
               (:file "tests/expert")
               (:file "tests/expert-orchestration")
               (:file "tests/expert-state-snapshot")
               (:file "tests/expert-plan")
               (:file "tests/expert-recon")
               (:file "tests/expert-loop")
               (:file "tests/expert-objective")
               (:file "tests/expert-extension")
               (:file "tests/expert-selection")
               (:file "tests/expert-budget")
               (:file "tests/expert-inspection")
               (:file "tests/expert-selection-inspection"))
  :perform (test-op (op system)
             (declare (ignore op system))
             (uiop:symbol-call :hackmode-tests :run-tests)
             (uiop:symbol-call :hackmode-tests :run-functions-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-orchestration-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-state-snapshot-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-plan-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-recon-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-loop-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-objective-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-extension-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-selection-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-budget-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-inspection-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-selection-inspection-tests)))
