(asdf:defsystem :hackmode-tests
  :description "Regression tests for Hackmode core state, asset lifecycle, and expert reasoning"
  :depends-on (#:hackmode #:hackmode-database)
  :serial t
  :components ((:file "tests/core-state")
               (:file "tests/investigation-views")
               (:file "tests/functions")
               (:file "tests/expert")
               (:file "tests/expert-orchestration")
               (:file "tests/expert-state-snapshot")
               (:file "tests/expert-plan")
               (:file "tests/expert-recon")
               (:file "tests/expert-loop")
               (:file "tests/expert-loop-scope-copy")
               (:file "tests/expert-objective")
               (:file "tests/expert-extension")
               (:file "tests/expert-selection")
               (:file "tests/expert-selection-copy")
               (:file "tests/expert-budget")
               (:file "tests/expert-inspection")
               (:file "tests/expert-inspection-copy")
               (:file "tests/expert-run-inspection-copy")
               (:file "tests/expert-transition-inspection")
               (:file "tests/expert-selection-inspection")
               (:file "tests/expert-budget-inspection")
               (:file "tests/expert-direct-candidate")
               (:file "tests/capture-provider")
               (:file "tests/http-transport-profile")
               (:file "tests/visual-evidence-outbox")
               (:file "tests/http-requester"))
  :perform (test-op (op system)
             (declare (ignore op system))
             (uiop:symbol-call :hackmode-tests :run-tests)
             (uiop:symbol-call :hackmode-tests :run-investigation-view-tests)
             (uiop:symbol-call :hackmode-tests :run-functions-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-orchestration-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-state-snapshot-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-plan-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-recon-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-loop-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-loop-scope-copy-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-objective-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-extension-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-selection-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-selection-copy-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-budget-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-inspection-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-inspection-copy-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-run-inspection-copy-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-transition-inspection-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-selection-inspection-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-budget-inspection-tests)
             (uiop:symbol-call :hackmode-tests :run-expert-direct-candidate-tests)
             (uiop:symbol-call :hackmode-tests :run-capture-provider-tests)
             (uiop:symbol-call :hackmode-http-transport-profile-tests
                               :run-http-transport-profile-tests)
             (uiop:symbol-call :hackmode-visual-evidence-outbox-tests
                               :run-visual-evidence-outbox-tests)
             (uiop:symbol-call :hackmode-http-requester-tests
                               :run-http-requester-tests)))
