(uiop:define-package :hackmode
  (:import-from :serapeum :dict :@)
  (:documentation "Core Hackmode runtime and compatibility API.")
  (:export
   :EXPLOIT-OPTION-DOCUMENTATION
   :EXPLOIT-NAME
   :USE
   :EXPLOIT-OPTIONS
   :EXPLOIT-OPTION-NAME
   :EXPLOIT-SETUP
   :UNIX-NOW
   :RUN-EXPLOIT
   :EXPLOIT-FUNC
   :EXPLOIT-HELP
   :EXPLOIT-PLATFORM
   :EXPLOIT-OPTION-TYPE
   :hackmode-init-file
   :hackmode-operations-database
   :RHOST
   :payloads
   :config-dir
   :wordlist-dir
   :wordlist-alist
   :wordlist
   :target-platform
   :socks5-proxy-list
   :http-proxy-list
   :exploits-dir
   :history-path
   :prompt
   :*startup-hook*
   :init-database
   :put-doc
   :put-docs
   :*db*
   :*operations-database*
   :meta
   :output
   :host
   :port
   :finding
   :url
   :cert
   :*api-common-patterns*
   :find-api
   :find-apis
   :*exploits*
   :*current-exploit*
   :exploit-option
   :exploit
   :operation
   :operation-dir
   :operation-name
   :operation-description
   :domain
   :domain-name
   :domain-type
   :domain-ips
   :doman-zone
   :use-operation
   :parse-url
   :url-query
   :url-path
   :url-port
   :url-host
   :url-scheme
   :*interactive*
   :*finding-hook*
   :*domain-hook*
   :flatten
   :*current-operation*
   :current-operation
   :new-operation
   :select-operation
   :list-operations
   :operation-status
   :ensure-operations-database-open
   :make-command
   :doc-id
   :doc-tags
   :doc-type
   :doc-operation
   :doc-date-updated
   :doc-date-added
   :doc-output
   :doc-tool
   :doc-host
   :doc-ip
   :doc-port
   :doc-services
   :finding-id
   :finding-doc
   :finding-finding-type
   :finding-data
   :cert-not-before
   :cert-not-after
   :cert-common-name
   :cert-org-unit-name
   :cert-locality
   :cert-country
   :cert-province
   ;; Asset protocol
   :asset-event
   :asset-event-event-type
   :asset-event-asset
   :asset-event-operation
   :asset-event-timestamp
   :*asset-event-hook*
   :asset-kind
   :normalize-asset
   :asset-canonical-value
   :asset-deterministic-id
   :asset-requires-parent-p
   :asset->starintel-document
   :asset->starintel-json
   :asset-starintel-id
   :asset-starintel-supported-p
   :*starintel-dataset*
   :store-asset
   :discover-asset
   :record-recon-asset
   :query-assets
   :publish-asset-event
   :publish-legacy-asset-hook
   :subscribe-asset-events
   ;; Capability/provider protocol
   :capability-provider
   :capability-provider-capability
   :capability-provider-name
   :capability-provider-input-type
   :capability-provider-output-types
   :capability-provider-priority
   :provider-job-result
   :provider-job-result-id
   :provider-job-result-capability
   :provider-job-result-provider
   :provider-job-result-input
   :provider-job-result-assets
   :provider-job-result-created-count
   :provider-job-result-state
   :provider-job-result-error
   :provider-job-result-started-at
   :provider-job-result-finished-at
   :*capability-providers*
   :register-capability-provider
   :unregister-capability-provider
   :clear-capability-providers
   :list-capability-providers
   :find-capability-provider
   :provider-job-id
   :execute-provider-job
   :run-capability
   ;; Tool schema and mappings
   :tool-target-shape
   :tool-target-shape-name
   :tool-target-shape-description
   :tool-target-shape-examples
   :tool-target-shape-options
   :tool-argument
   :tool-argument-name
   :tool-argument-type
   :tool-argument-required-p
   :tool-argument-repeatable-p
   :tool-argument-default
   :tool-argument-flag
   :tool-argument-description
   :tool-mapping
   :tool-mapping-capability
   :tool-mapping-provider
   :tool-mapping-executable
   :tool-mapping-target-shapes
   :tool-mapping-arguments
   :tool-mapping-example-targets
   :tool-mapping-platforms
   :tool-mapping-packages
   :tool-mapping-fixed-arguments
   :tool-mapping-metadata
   :tool-command-input
   :tool-command-input-raw-target
   :tool-command-input-target
   :tool-command-input-target-shape
   :tool-command-input-arguments
   :tool-command-input-target-options
   :*tool-target-shapes*
   :*tool-mappings*
   :register-tool-target-shape
   :define-target-shape
   :find-tool-target-shape
   :list-tool-target-shapes
   :tool-target-shape-accepts-p
   :make-tool-arg
   :register-tool-mapping
   :define-tool-mapping
   :find-tool-mapping
   :list-tool-mappings
   :make-validated-tool-command-input
   :tool-mapping-available-p
   :kali-linux-p
   :build-tool-command-argv
   :register-kali-command-tool-providers
   ;; Replayable actor journal
   :hackmode-actor-event-conflict
   :hackmode-actor-event-conflict-event-id
   :*actor-event-sink*
   :append-hackmode-actor-event
   :replay-hackmode-actor-events
   ;; Persistent StarIntel outbox
   :+outbox-database-name+
   :outbox-entry
   :outbox-entry-id
   :outbox-entry-document-id
   :outbox-entry-dtype
   :outbox-entry-operation
   :outbox-entry-payload
   :outbox-entry-state
   :outbox-entry-attempts
   :outbox-entry-created-at
   :outbox-entry-updated-at
   :outbox-entry-next-attempt-at
   :outbox-entry-last-error
   :outbox-entry-last-status
   :outbox-entry-ack-kind
   :outbox-entry-acknowledged-at
   :outbox-transport-error
   :outbox-transport-error-message
   :*outbox-max-attempts*
   :*outbox-backoff-base-seconds*
   :*outbox-backoff-max-seconds*
   :*starintel-ingest-base-url*
   :outbox-payload-id
   :enqueue-starintel-json
   :enqueue-asset-for-starintel
   :visual-evidence->starintel-json
   :enqueue-visual-evidence-for-starintel
   :fetch-outbox-entry
   :list-outbox-entries
   :outbox-backoff-seconds
   :outbox-due-p
   :process-outbox-entry
   :drain-outbox
   :make-starintel-http-transport
   ;; Shared actor runtime
   :*hackmode-actor-system*
   :*hackmode-actor*
   :*tool-actors*
   :*outbox-actor*
   :*provider-supervisor*
   :ensure-hackmode-actor-system
   :stop-hackmode-actor-system
   :tool-actor-name
   :list-tool-actor-descriptors
   :describe-tool-actor
   :find-tool-actor
   :sync-tool-actors
   :dispatch-tool-actor
   :start-hackmode-actor
   :ask-hackmode-actor
   ;; StarIntel registry bridge
   :*starintel-actor-registry-base-url*
   :*starintel-actor-registry-path*
   :*starintel-actor-registry-authority*
   :*starintel-actor-registry-headers-function*
   :hackmode-actor-manifest
   :encode-hackmode-actor-manifest
   :register-hackmode-with-starintel
   :refresh-hackmode-starintel-registration
   ;; Outbox actor
   :start-outbox-actor
   :drain-outbox-async
   ;; Provider actor
   :start-provider-supervisor
   :dispatch-capability
   ;; Capture provider lifecycle
   :capture-process-spec
   :capture-process-spec-operation-id
   :capture-process-spec-capture-session-id
   :capture-process-spec-endpoint
   :capture-process-spec-spool-id
   :capture-process-spec-spool-path
   :capture-process-spec-program
   :capture-process-spec-arguments
   :capture-service
   :capture-service-operation-id
   :capture-service-capture-session-id
   :capture-service-endpoint
   :capture-service-spool-id
   :capture-service-version
   :capture-service-state
   :capture-service-process-id
   :capture-service-restart-count
   :capture-service-max-restarts
   :capture-service-failure-class
   :capture-service-last-error
   :start-capture-service
   :note-capture-process-exit
   :stop-capture-service
   ;; Capture replay
   :ipx-replay-result
   :ipx-replay-result-operation-id
   :ipx-replay-result-capture-session-id
   :ipx-replay-result-source-id
   :ipx-replay-result-start-offset
   :ipx-replay-result-end-offset
   :ipx-replay-result-committed-count
   :ipx-replay-result-quarantine-count
   :ipx-replay-result-truncated-p
   :ipx-spool-fingerprint-mismatch
   :ipx-spool-fingerprint-mismatch-offset
   :ipx-spool-fingerprint-mismatch-expected-fingerprint
   :ipx-spool-fingerprint-mismatch-actual-fingerprint
   :ipx-spool-fingerprint-mismatch-reason
   :replay-ipx-http-spool
   ;; Optional Prolog expert layer
   :*expert-program*
   :expert-unavailable
   :expert-unavailable-program
   :expert-query-failed
   :expert-query-failed-status
   :expert-query-failed-stderr
   :expert-recommendation
   :expert-recommendation-capability
   :expert-recommendation-provider
   :expert-recommendation-priority
   :expert-available-p
   :expert-snapshot
   :expert-classify-target
   :expert-recommend-capabilities))

(in-package :hackmode)