(uiop:define-package :hackmode
  (:import-from :serapeum :dict :@)
  (:documentation "Core Hackmode runtime and compatibility API.")
  (:export
   :EXPLOIT-OPTION-DOCUMENTATION
   :EXPLOIT-NAME
   :USE
   :EXPLOIT-OPTIONS
   :EXPLOIT-OPTION-NAME
   :EXPLOIT-SETUP
   :UNIX-NOW
   :RUN-EXPLOIT
   :EXPLOIT-FUNC
   :EXPLOIT-HELP
   :EXPLOIT-PLATFORM
   :EXPLOIT-OPTION-TYPE
   :hackmode-init-file
   :hackmode-operations-database
   :RHOST
   :payloads
   :config-dir
   :wordlist-dir
   :wordlist-alist
   :wordlist
   :target-platform
   :socks5-proxy-list
   :http-proxy-list
   :exploits-dir
   :history-path
   :prompt
   :*startup-hook*
   :init-database
   :put-doc
   :put-docs
   :*db*
   :*operations-database*
   :meta
   :output
   :host
   :port
   :finding
   :url
   :cert
   :*api-common-patterns*
   :find-api
   :find-apis
   :*exploits*
   :*current-exploit*
   :exploit-option
   :exploit
   :operation
   :operation-dir
   :operation-name
   :operation-description
   :domain
   :domain-name
   :domain-type
   :domain-ips
   :doman-zone
   :use-operation
   :parse-url
   :url-query
   :url-path
   :url-port
   :url-host
   :url-scheme
   :*interactive*
   :*finding-hook*
   :*domain-hook*
   :flatten
   :*current-operation*
   :current-operation
   :new-operation
   :select-operation
   :list-operations
   :operation-status
   :ensure-operations-database-open
   :make-command
   :doc-id
   :doc-tags
   :doc-type
   :doc-operation
   :doc-date-updated
   :doc-date-added
   :doc-output
   :doc-tool
   :doc-host
   :doc-ip
   :doc-port
   :doc-services
   :finding-id
   :finding-doc
   :finding-finding-type
   :finding-data
   :cert-not-before
   :cert-not-after
   :cert-common-name
   :cert-org-unit-name
   :cert-locality
   :cert-country
   :cert-province
   ;; Asset protocol
   :asset-event
   :asset-event-event-type
   :asset-event-asset
   :asset-event-operation
   :asset-event-timestamp
   :*asset-event-hook*
   :asset-kind
   :normalize-asset
   :asset-canonical-value
   :asset-deterministic-id
   :asset-requires-parent-p
   :asset->starintel-document
   :asset->starintel-json
   :asset-starintel-id
   :asset-starintel-supported-p
   :*starintel-dataset*
   :store-asset
   :discover-asset
   :record-recon-asset
   :query-assets
   :publish-asset-event
   :publish-legacy-asset-hook
   :subscribe-asset-events))

(in-package :hackmode)
