(uiop:define-package :hackmode-database
  (:nicknames :hack-db)
  (:use :cl)
  (:export
   #:*db*
   #:execution-graph-validation-error
   #:execution-record
   #:execution-record-kind
   #:execution-record-operation-id
   #:execution-record-run-id
   #:execution-record-call-id
   #:execution-record-record-id
   #:execution-record-capability-id
   #:execution-record-status
   #:execution-record-payload
   #:execution-record-provenance
   #:make-tool-call-record
   #:make-tool-result-record
   #:validate-tool-result-link
   #:execution-graph-name
   #:execution-record->tek9-node
   #:tool-result-link-edge
   #:persist-execution-record
   #:persist-tool-execution
   #:operational-kb-validation-error
   #:operational-kb-entry
   #:operational-kb-entry-kind
   #:operational-kb-entry-operation-id
   #:operational-kb-entry-run-id
   #:operational-kb-entry-expert-id
   #:operational-kb-entry-expert-version
   #:operational-kb-entry-record-id
   #:operational-kb-entry-key
   #:operational-kb-entry-value
   #:operational-kb-entry-target-assertion-id
   #:operational-kb-entry-evidence-ids
   #:operational-kb-entry-provenance
   #:make-operational-kb-assertion
   #:make-operational-kb-retraction
   #:operational-kb-graph-name
   #:operational-kb-root-id
   #:operational-kb-entry->tek9-node
   #:operational-kb-membership-edge
   #:operational-kb-retraction-edge
   #:persist-operational-kb-entry
   #:fetch-operational-kb-entry
   #:put-doc
   #:put-docs))
