(uiop:define-package :hackmode-database
  (:nicknames :hack-db)
  (:use :cl)
  (:export
   #:*db*
   #:persistence-replay-conflict
   #:persistence-replay-conflict-record-kind
   #:persistence-replay-conflict-record-id
   #:persistence-replay-conflict-database-name
   #:persistence-replay-conflict-existing
   #:persistence-replay-conflict-incoming
   #:persist-graph-node-replay-safe
   #:persist-graph-edge-replay-safe
   #:persist-graph-nodes-replay-safe
   #:persist-graph-edges-replay-safe
   #:execution-graph-validation-error
   #:execution-record
   #:execution-record-kind
   #:execution-record-operation-id
   #:execution-record-run-id
   #:execution-record-call-id
   #:execution-record-record-id
   #:execution-record-capability-id
   #:execution-record-status
   #:execution-record-payload
   #:execution-record-provenance
   #:make-tool-call-record
   #:make-tool-result-record
   #:make-http-exchange-record
   #:make-capture-checkpoint-record
   #:make-capture-quarantine-record
   #:make-capture-source-rotation-record
   #:validate-tool-result-link
   #:execution-graph-name
   #:execution-record->tek9-node
   #:tek9-node->execution-record
   #:tool-result-link-edge
   #:persist-execution-record
   #:persist-tool-execution
   #:fetch-operation-execution-records
   #:fetch-latest-capture-checkpoint
   #:fetch-capture-quarantine-records
   #:fetch-capture-source-rotations
   #:visual-evidence-record
   #:visual-evidence-record-operation-id
   #:visual-evidence-record-run-id
   #:visual-evidence-record-job-id
   #:visual-evidence-record-record-id
   #:visual-evidence-record-asset-id
   #:visual-evidence-record-requested-url
   #:visual-evidence-record-final-url
   #:visual-evidence-record-screenshot-evidence-ref
   #:visual-evidence-record-screenshot-digest
   #:visual-evidence-record-captured-at
   #:visual-evidence-record-title
   #:visual-evidence-record-http-status
   #:visual-evidence-record-viewport
   #:visual-evidence-record-client-profile-id
   #:visual-evidence-record-browser-id
   #:visual-evidence-record-browser-version
   #:visual-evidence-record-duration-ms
   #:visual-evidence-record-body-digest
   #:visual-evidence-record-technology-hints
   #:visual-evidence-record-capture-session-id
   #:visual-evidence-record-exchange-id
   #:visual-evidence-record-failure-classification
   #:visual-evidence-record-provenance
   #:make-visual-evidence-record
   #:visual-evidence-graph-name
   #:visual-evidence-record->tek9-node
   #:tek9-node->visual-evidence-record
   #:persist-visual-evidence-record
   #:fetch-visual-evidence-record
   #:fetch-visual-evidence-records
   #:operational-kb-validation-error
   #:operational-kb-entry
   #:operational-kb-entry-kind
   #:operational-kb-entry-operation-id
   #:operational-kb-entry-run-id
   #:operational-kb-entry-expert-id
   #:operational-kb-entry-expert-version
   #:operational-kb-entry-record-id
   #:operational-kb-entry-key
   #:operational-kb-entry-value
   #:operational-kb-entry-target-assertion-id
   #:operational-kb-entry-evidence-ids
   #:operational-kb-entry-provenance
   #:make-operational-kb-assertion
   #:make-operational-kb-retraction
   #:operational-kb-graph-name
   #:operational-kb-root-id
   #:operational-kb-entry->tek9-node
   #:tek9-node->operational-kb-entry
   #:operational-kb-membership-edge
   #:operational-kb-retraction-edge
   #:persist-operational-kb-entry
   #:fetch-operational-kb-entry
   #:fetch-operational-kb-entries
   #:fetch-effective-operational-kb-assertions
   #:make-execution-outcome-kb-candidate
   #:+operational-kb-seed-import-limit+
   #:+operational-kb-seed-kinds+
   #:make-operational-kb-seed-assertions
   #:persist-operational-kb-seed-values
   #:long-term-kb-validation-error
   #:long-term-kb-promotion
   #:long-term-kb-promotion-record-id
   #:long-term-kb-promotion-source-operation-id
   #:long-term-kb-promotion-source-assertion-id
   #:long-term-kb-promotion-source-run-id
   #:long-term-kb-promotion-source-expert-id
   #:long-term-kb-promotion-source-expert-version
   #:long-term-kb-promotion-source-evidence-ids
   #:long-term-kb-promotion-key
   #:long-term-kb-promotion-value
   #:long-term-kb-promotion-promoted-by
   #:long-term-kb-promotion-promoter-version
   #:long-term-kb-promotion-evidence-ids
   #:long-term-kb-promotion-provenance
   #:make-long-term-kb-promotion
   #:long-term-kb-graph-name
   #:long-term-kb-root-id
   #:long-term-kb-promotion->tek9-node
   #:tek9-node->long-term-kb-promotion
   #:long-term-kb-membership-edge
   #:long-term-kb-source-edge
   #:persist-long-term-kb-promotion
   #:fetch-long-term-kb-promotion
   #:fetch-long-term-kb-promotions
   #:global-kb-validation-error
   #:global-kb-export
   #:global-kb-export-record-id
   #:global-kb-export-source-promotion-id
   #:global-kb-export-source-operation-id
   #:global-kb-export-source-assertion-id
   #:global-kb-export-source-run-id
   #:global-kb-export-source-expert-id
   #:global-kb-export-source-expert-version
   #:global-kb-export-source-evidence-ids
   #:global-kb-export-promotion-evidence-ids
   #:global-kb-export-key
   #:global-kb-export-value
   #:global-kb-export-exported-by
   #:global-kb-export-exporter-version
   #:global-kb-export-evidence-ids
   #:global-kb-export-provenance
   #:make-global-kb-export
   #:global-kb-graph-name
   #:global-kb-root-id
   #:global-kb-export->tek9-node
   #:tek9-node->global-kb-export
   #:global-kb-membership-edge
   #:global-kb-source-edge
   #:persist-global-kb-export
   #:fetch-global-kb-export
   #:fetch-global-kb-exports
   #:put-doc
   #:put-docs))